name: Sync to GCP Bucket
on:
  push:
    branches:
      - main  # or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # This step checks out your repository to the runner

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Sync files to Bucket
      run: |
        gsutil -m rm gs://cloud-resume-challenge-gcp/**  # This removes all files from your bucket
        gsutil -m cp -r . gs://cloud-resume-challenge-gcp/  # This copies all new files from your repository to the bucket
